// [
//     'bắp tay',   'cardio',
//     'cẳng chân', 'cẳng tay',
//     'eo',        'lưng',
//     'neck',      'ngực',
//     'vai',       'đùi'
// ]

export const images = {
    'ngực': require('../assets/images/chest.jpg'),
    'lưng': require('../assets/images/back.jpg'),
    "cẳng tay": require('../assets/images/lower_arms.jpg'),
    "cẳng chân": require('../assets/images/lower_legs.jpg'),
    'cơ cổ': require('../assets/images/neck.jpg'),
    "tay": require('../assets/images/upper_arms.jpg'),
    "chân": require('../assets/images/lower_legs.jpg'),
    vai: require('../assets/images/shoulders.jpg'),
    plan_background: require('../assets/images/plan_background.jpg'),
    "vai": require('../assets/images/shoulders.jpg'),
    "bắp tay": require('../assets/images/upper_arms.jpg'),
    "đùi": require('../assets/images/upper_legs.jpg'),
    eo: require('../assets/images/waist.jpg'),
    "bụng": require('../assets/images/waist.jpg'),
    butt: require('../assets/images/butt.jpg'),
    "stronglift a": require('../assets/images/power_lifting.jpg'),
    "stronglift b": require('../assets/images/power_lifting.jpg'),
    "thân trên": require('../assets/images/upper_body.jpg'),
    "toàn thân": require('../assets/images/full_body.jpg'),
    cardio: require('../assets/images/cardio.jpg'),
    "cardio": require('../assets/images/cardio.jpg'),
    no_result: require('../assets/images/no-result.png'),
    welcome_image: require('../assets/images/welcome_image.jpg'),
    golden_cup: require('../assets/images/golden_cup.png'),
    smile_emoji: require('../assets/images/smile_emoji.png'),
    male: require('../assets/images/male.jpg'),
    female: require('../assets/images/female.jpg'),
    fitness_male: require('../assets/images/fitness_male.jpg'),
    fitness_female: require('../assets/images/fitness_female.jpg'),
    "3d_male": require('../assets/images/3d_male.jpg'),
    "3d_female": require('../assets/images/3d_female.jpg'),
};